<?xml version="1.0" encoding="ASCII"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="statemachines" nsURI="http://org.tetrabox.examples.statemachines.interpretedstatemachines/statemachines/" nsPrefix="statemachines">
    <eClassifiers xsi:type="ecore:EClass" name="CustomSystem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="statemachine" lowerBound="1" eType="/0/almostuml/StateMachine" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1" eType="/0/CustomEvent" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CustomEvent" eSuperTypes="/0/almostuml/Event"/>
    <eClassifiers xsi:type="ecore:EClass" name="EventOccurrence">
      <eAnnotations source="aspect"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="Iterable" instanceClassName="java.lang.Iterable">
      <eAnnotations source="aspect"/>
    </eClassifiers>
    <eSubpackages name="almostuml" nsURI="http://org.tetrabox.examples.statemachines.interpretedstatemachines/statemachines/almostuml/" nsPrefix="almostuml">
      <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="StateMachine" eSuperTypes="/0/almostuml/NamedElement">
        <eOperations name="run">
          <eAnnotations source="aspect"/>
        </eOperations>
        <eOperations name="eventOccurrenceReceived">
          <eAnnotations source="aspect"/>
          <eParameters name="eventType" eType="/0/CustomEvent"/>
        </eOperations>
        <eOperations name="terminate">
          <eAnnotations source="aspect"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="regions" lowerBound="1" upperBound="-1" eType="/0/almostuml/Region" containment="true" eOpposite="/0/almostuml/Region/stateMachine"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Region">
        <eOperations name="enter">
          <eAnnotations source="aspect"/>
          <eParameters name="enteringTransition" eType="/0/almostuml/Transition"/>
          <eParameters name="eventOccurrence" eType="/0/EventOccurrence"/>
        </eOperations>
        <eOperations name="exit">
          <eAnnotations source="aspect"/>
          <eParameters name="exitingTransition" eType="/0/almostuml/Transition"/>
          <eParameters name="eventOccurrence" eType="/0/EventOccurrence"/>
        </eOperations>
        <eOperations name="terminate">
          <eAnnotations source="aspect"/>
        </eOperations>
        <eOperations name="getContainingStateMachine" eType="/0/almostuml/StateMachine">
          <eAnnotations source="aspect"/>
        </eOperations>
        <eOperations name="getActiveVertice" eType="/0/Iterable">
          <eAnnotations source="aspect"/>
        </eOperations>
        <eOperations name="contains">
          <eAnnotations source="aspect"/>
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
          <eParameters name="vertex" eType="/0/almostuml/Vertex"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="vertice" upperBound="-1" eType="/0/almostuml/Vertex" containment="true" eOpposite="/0/almostuml/Vertex/container"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1" eType="/0/almostuml/Transition" containment="true" eOpposite="/0/almostuml/Transition/container"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="stateMachine" eType="/0/almostuml/StateMachine" eOpposite="/0/almostuml/StateMachine/regions"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="state" eType="/0/almostuml/State" eOpposite="/0/almostuml/State/regions"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="/0/almostuml/Vertex">
        <eOperations name="enter">
          <eAnnotations source="aspect"/>
          <eParameters name="enteringTransition" eType="/0/almostuml/Transition"/>
          <eParameters name="eventOccurrence" eType="/0/EventOccurrence"/>
          <eParameters name="leastCommonAncestor" eType="/0/almostuml/Region"/>
        </eOperations>
        <eOperations name="exit">
          <eAnnotations source="aspect"/>
          <eParameters name="exitingTransition" eType="/0/almostuml/Transition"/>
          <eParameters name="eventOccurrence" eType="/0/EventOccurrence"/>
          <eParameters name="leastCommonAncestor" eType="/0/almostuml/Region"/>
        </eOperations>
        <eOperations name="enterRegions">
          <eAnnotations source="aspect"/>
          <eParameters name="enteringTransition" eType="/0/almostuml/Transition"/>
          <eParameters name="eventOccurrence" eType="/0/EventOccurrence"/>
        </eOperations>
        <eOperations name="terminate">
          <eAnnotations source="aspect"/>
        </eOperations>
        <eOperations name="getActiveVertice" upperBound="-1" eType="/0/almostuml/Vertex">
          <eAnnotations source="aspect"/>
        </eOperations>
        <eOperations name="hasCompleted">
          <eAnnotations source="aspect"/>
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        </eOperations>
        <eOperations name="complete">
          <eAnnotations source="aspect"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="regions" upperBound="-1" eType="/0/almostuml/Region" containment="true" eOpposite="/0/almostuml/Region/state"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Vertex" eSuperTypes="/0/almostuml/NamedElement">
        <eOperations name="enter">
          <eAnnotations source="aspect"/>
          <eParameters name="enteringTransition" eType="/0/almostuml/Transition"/>
          <eParameters name="eventOccurrence" eType="/0/EventOccurrence"/>
          <eParameters name="leastCommonAncestor" eType="/0/almostuml/Region"/>
        </eOperations>
        <eOperations name="exit">
          <eAnnotations source="aspect"/>
          <eParameters name="exitingTransition" eType="/0/almostuml/Transition"/>
          <eParameters name="eventOccurrence" eType="/0/EventOccurrence"/>
          <eParameters name="leastCommonAncestor" eType="/0/almostuml/Region"/>
        </eOperations>
        <eOperations name="terminate">
          <eAnnotations source="aspect"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="/0/almostuml/Region" eOpposite="/0/almostuml/Region/vertice"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingTransitions" upperBound="-1" eType="/0/almostuml/Transition" eOpposite="/0/almostuml/Transition/source"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="incomingTransitions" upperBound="-1" eType="/0/almostuml/Transition" eOpposite="/0/almostuml/Transition/target"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="/0/almostuml/NamedElement">
        <eOperations name="fire">
          <eAnnotations source="aspect"/>
          <eParameters name="eventOccurrence" eType="/0/EventOccurrence"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1" eType="/0/almostuml/Vertex" eOpposite="/0/almostuml/Vertex/outgoingTransitions"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1" eType="/0/almostuml/Vertex" eOpposite="/0/almostuml/Vertex/incomingTransitions"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="triggers" upperBound="-1" eType="/0/almostuml/Trigger" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="container" lowerBound="1" eType="/0/almostuml/Region" eOpposite="/0/almostuml/Region/transitions"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="/0/almostuml/TransitionKind"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Trigger" eSuperTypes="/0/almostuml/NamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="event" lowerBound="1" eType="/0/almostuml/Event"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Event" abstract="true" eSuperTypes="/0/almostuml/NamedElement"/>
      <eClassifiers xsi:type="ecore:EClass" name="CompletionEvent" eSuperTypes="/0/almostuml/Event">
        <eStructuralFeatures xsi:type="ecore:EReference" name="state" lowerBound="1" eType="/0/almostuml/State"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="FinalState" eSuperTypes="/0/almostuml/State">
        <eOperations name="enter">
          <eAnnotations source="aspect"/>
          <eParameters name="enteringTransition" eType="/0/almostuml/Transition"/>
          <eParameters name="eventOccurrence" eType="/0/EventOccurrence"/>
          <eParameters name="leastCommonAncestor" eType="/0/almostuml/Region"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Pseudostate" eSuperTypes="/0/almostuml/Vertex">
        <eOperations name="enter">
          <eAnnotations source="aspect"/>
          <eParameters name="enteringTransition" eType="/0/almostuml/Transition"/>
          <eParameters name="eventOccurrence" eType="/0/EventOccurrence"/>
          <eParameters name="leastCommonAncestor" eType="/0/almostuml/Region"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" lowerBound="1" eType="/0/almostuml/PseudostateKind"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="PseudostateKind">
        <eLiterals name="initial"/>
        <eLiterals name="join" value="1"/>
        <eLiterals name="fork" value="2"/>
        <eLiterals name="terminate" value="3"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="TransitionKind">
        <eLiterals name="internal"/>
        <eLiterals name="local" value="1"/>
        <eLiterals name="external" value="2"/>
      </eClassifiers>
    </eSubpackages>
  </ecore:EPackage>
  <ecore:EPackage name="statemachinesexecutiondata" nsURI="http://org.tetrabox.examples.statemachines.interpretedstatemachines/statemachinesexecutiondata/" nsPrefix="statemachinesexecutiondata">
    <eClassifiers xsi:type="ecore:EClass" name="EventOccurrence">
      <eStructuralFeatures xsi:type="ecore:EReference" name="event" lowerBound="1" eType="/0/CustomEvent"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
